---
title: Understanding async/await
---

If you aren't very familiar with ECMAScript 2017, you may not know about async/await. It's a useful way to handle Promises in a hoisted manner. It's also slightly faster and increases overall readability.

## How do Promises work?

Before we can get into async/await, you should know what Promises are and how they work because async/await is just a way to handle Promises. If you know what Promises are and how to deal with them, you can skip this part.

Promises are a way to handle asynchronous tasks in JavaScript; they are the newer alternative to callbacks. A Promise has many similarities to a progress bar; they represent an unfinished and ongoing process. An excellent example of this is a request to a server (e.g., discord.js sends requests to Discord's API).

A Promise can have three states; pending, resolved, and rejected.

- The **pending** state means that the Promise still is ongoing and neither resolved nor rejected.
- The **resolved** state means that the Promise is done and executed without any errors.
- The **rejected** state means that the Promise encountered an error and could not execute correctly.

One important thing to know is that a Promise can only have one state simultaneously; it can never be pending and resolved, rejected and resolved, or pending and rejected. You may be asking, "How would that look in code?". Here is a small example:

<Callout>
	This example uses ES6 code. If you do not know what that is, you should read up on that [here](./es6-syntax).
</Callout>

```js
function deleteMessages(amount) {
	// [!code word:Promise]
	return new Promise((resolve, reject) => {
		if (amount > 10) return reject(new Error("You can't delete more than 10 Messages at a time."));
		setTimeout(() => resolve('Deleted 10 messages.'), 2_000);
	});
}

deleteMessages(5)
	// [!code word:then]
	.then((value) => {
		// `deleteMessages` is complete and has not encountered any errors
		// the resolved value will be the string "Deleted 10 messages"
	})
	// [!code word:catch]
	.catch((error) => {
		// `deleteMessages` encountered an error
		// the error will be an Error Object
	});
```

In this scenario, the `deleteMessages` function returns a Promise. The `.then()` method will trigger if the Promise resolves, and the `.catch()` method if the Promise rejects. In the `deleteMessages` function, the Promise is resolved after 2 seconds with the string "Deleted 10 messages.", so the `.catch()` method will never be executed. You can also pass the `.catch()` function as the second parameter of `.then()`.

## How to implement async/await

### Theory

The following information is essential to know before working with async/await. You can only use the `await` keyword inside a function declared as `async` (you put the `async` keyword before the `function` keyword or before the parameters when using a callback function).

A simple example would be:

```js
// [!code word:async]
async function declaredAsAsync() {
	// ...
}
```

or

```js
// [!code word:async]
const declaredAsAsync = async () => {
	// ...
};
```

You can use that as well if you use the arrow function as an event listener.

```js
client.on('event', async (first, last) => {
	// ...
});
```

An important thing to know is that a function declared as `async` will always return a Promise. In addition to this, if you return something, the Promise will resolve with that value, and if you throw an error, it will reject the Promise with that error.

### Execution with discord.js code

Now that you know how Promises work and what they are used for, let's look at an example that handles multiple Promises. Let's say you want to react with letters (regional indicators) in a specific order. For this example, here's a basic template for a discord.js bot with some ES6 adjustments.

```js title="promise-example.js" lineNumbers
const { Client, Events, GatewayIntentBits } = require('discord.js');

const client = new Client({ intents: [GatewayIntentBits.Guilds] });

client.once(Events.ClientReady, () => {
	console.log('I am ready!');
});

client.on(Events.InteractionCreate, (interaction) => {
	if (!interaction.isChatInputCommand()) return;

	if (interaction.commandName === 'react') {
		// ...
	}
});

client.login('your-token-goes-here');
```

If you don't know how Node.js asynchronous execution works, you would probably try something like this:

```js title="promise-example.js" lineNumbers=9
client.on(Events.InteractionCreate, (interaction) => {
	// ...
	// [!code focus:7]
	if (commandName === 'react') {
		const response = interaction.reply({ content: 'Reacting!', withResponse: true }); // [!code ++:5]
		const { message } = response.resource;
		message.react('ðŸ‡¦');
		message.react('ðŸ‡§');
		message.react('ðŸ‡¨');
	}
});
```

But since all of these methods are started at the same time, it would just be a race to which server request finished first, so there would be no guarantee that it would react at all (if the message isn't fetched) or in the order you wanted it to. In order to make sure it reacts after the message is sent and in order (a, b, c), you'd need to use the `.then()` callback from the Promises that these methods return. The code would look like this:

```js title="promise-example.js" lineNumbers=9
client.on(Events.InteractionCreate, (interaction) => {
	// ...
	if (commandName === 'react') {
		interaction.reply({ content: 'Reacting!', withResponse: true }).then((response) => {
			const { message } = response.resource;
			message.react('ðŸ‡¦'); // [!code --:3]
			message.react('ðŸ‡§');
			message.react('ðŸ‡¨');
			message // [!code ++:7]
				.react('ðŸ‡¦')
				.then(() => message.react('ðŸ‡§'))
				.then(() => message.react('ðŸ‡¨'))
				.catch((error) => {
					// handle failure of any Promise rejection inside here
				});
		});
	}
});
```

In this piece of code, the Promises are [chain resolved](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#Chaining) with each other, and if one of the Promises gets rejected, the function passed to `.catch()` gets called. Here's the same code but with async/await:

```js title="promise-example.js" lineNumbers=9
client.on(Events.InteractionCreate, async (interaction) => {
	// ...
	if (commandName === 'react') {
		const response = await interaction.reply({ content: 'Reacting!', withResponse: true });
		const { message } = response.resource;
		message.react('ðŸ‡¦'); // [!code --:3]
		message.react('ðŸ‡§');
		message.react('ðŸ‡¨');
		await message.react('ðŸ‡¦'); // [!code ++:3]
		await message.react('ðŸ‡§');
		await message.react('ðŸ‡¨');
	}
});
```

It's mostly the same code, but how would you catch Promise rejections now since `.catch()` isn't there anymore? That is also a useful feature with async/await; the error will be thrown if you await it so that you can wrap the awaited Promises inside a try/catch, and you're good to go.

```js title="promise-example.js" lineNumbers=9
client.on(Events.InteractionCreate, async (interaction) => {
	if (commandName === 'react') {
		// [!code ++]
		try {
			const response = await interaction.reply({ content: 'Reacting!', withResponse: true });
			const { message } = response.resource;
			await message.react('ðŸ‡¦');
			await message.react('ðŸ‡§');
			await message.react('ðŸ‡¨');
			// [!code ++:3]
		} catch (error) {
			// handle failure of any Promise rejection inside here
		}
	}
});
```

This code looks clean and is also easy to read.

So you may be asking, "How would I get the value the Promise resolved with?".

Let's look at an example where you want to delete a sent reply.

```js title="promise-example.js"
client.on(Events.InteractionCreate, (interaction) => {
	// ...
	if (commandName === 'delete') {
		interaction
			.reply({ content: 'This message will be deleted.', withResponse: true })
			.then((response) => setTimeout(() => response.resource.message.delete(), 10_000)) // [!code word:response]
			.catch((error) => {
				// handle error
			});
	}
});
```

The return value of a `.reply()` with the `withResponse` option set to `true` is a promise which resolves with `InteractionCallbackResponse`, but how would the same code with async/await look?

```js title="promise-example.js"
client.on(Events.InteractionCreate, async (interaction) => {
	if (commandName === 'delete') {
		try {
			const response = await interaction.reply({ content: 'This message will be deleted.', withResponse: true }); // [!code word:response]
			setTimeout(() => response.resource.message.delete(), 10_000);
		} catch (error) {
			// handle error
		}
	}
});
```

With async/await, you can assign the awaited function to a variable representing the returned value. Now you know how you use async/await.
